@url_dev=http://localhost:3052/v1/api/

### signup
POST {{url_dev}}/shop/signup
Content-Type: application/json

{
    "name": "anhvietdo",
    "email": "anhdvth2205005@fpt.edu.vn",
    "password": "abc123456"
}